const IMAGES = {
    alabama: require("./alabama-license.jpg"),
    alaska: require("./alaska-license.jpg"),
    arizona: require("./arizona-license.jpg"),
    arkansas: require("./arkansas-license.jpg"),
    california: require("./california-license.jpg"),
    colorado: require("./colorado-license.jpg"),
    connecticut: require("./connecticut-license.jpg"),
    delaware: require("./delaware-license.jpg"),
    florida: require("./florida-license.jpg"),
    georgia: require("./georgia-license.jpg"),
    hawaii: require("./hawaii-license.jpg"),
    idaho: require("./idaho-license.jpg"),
    illinois: require("./illinois-license.jpg"),
    indiana: require("./indiana-license.jpg"),
    iowa: require("./iowa-license.jpg"),
    kansas: require("./kansas-license.jpg"),
    kentucky: require("./kentucky-license.jpg"),
    louisiana: require("./louisiana-license.jpg"),
    maine: require("./maine-license.jpg"),
    maryland: require("./maryland-license.jpg"),
    massachusetts: require("./massachusetts-license.jpg"),
    michigan: require("./michigan-license.jpg"),
    minnesota: require("./minnesota-license.jpg"),
    mississippi: require("./mississippi-license.jpg"),
    missouri: require("./missouri-license.jpg"),
    montana: require("./montana-license.jpg"),
    nebraska: require("./nebraska-license.jpg"),
    nevada: require("./nevada-license.jpg"),
    "new hampshire": require("./newhampshire-license.jpg"),
    "new jersey": require("./newjersey-license.jpg"),
    "new mexico": require("./newmexico-license.jpg"),
    "new york": require("./newyork-license.jpg"),
    "north carolina": require("./northcarolina-license.jpg"),
    "north dakota": require("./northdakota-license.jpg"),
    ohio: require("./ohio-license.jpg"),
    oklahoma: require("./oklahoma-license.jpg"),
    oregon: require("./oregon-license.jpg"),
    pennsylvania: require("./pennsylvania-license.jpg"),
    "rhode island": require("./rhodeisland-license.jpg"),
    "south carolina": require("./southcarolina-license.jpg"),
    "south dakota": require("./southdakota-license.jpg"),
    tennessee: require("./tennessee-license.jpg"),
    texas: require("./texas-license.jpg"),
    utah: require("./utah-license.jpg"),
    vermont: require("./vermont-license.jpg"),
    virginia: require("./virginia-license.jpg"),
    washington: require("./washington-license.jpg"),
    "west virginia": require("./westvirginia-license.jpg"),
    wisconsin: require("./wisconsin-license.jpg"),
    wyoming: require("./wyoming-license.jpg"),
    map: require("./map.png"),
    logo: require("./logo.png"),
};

export default IMAGES;